<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
    <ProjectReference Include="../../src/Novolis.TemplateSmokeTest/Novolis.TemplateSmokeTest.csproj" />
  </ItemGroup>
</Project>
