<Project>
  <Import Project="$(MSBuildThisFileDirectory)..\Directory.Build.props" />
  <Import Project="$(MSBuildThisFileDirectory)..\build\Novolis.Smoketest.Documentation.props"
          Condition="Exists('$(MSBuildThisFileDirectory)..\build\Novolis.Smoketest.Documentation.props')" />
  <PropertyGroup>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" Condition="Exists('README.md')" />
  </ItemGroup>
</Project>
